apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: yossri1808/spring-k8s-app:1.0
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: app-config
